[project]
name = "leaning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.141.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "generativeai>=0.0.1",
    "google-genai>=2.21.0",
    "google-generativeai>=0.8.6",
    "imagekitio>=5.9.0",
    "jupyter>=1.1.1",
    "numpy>=2.5.2",
    "openai>=3.6.0",
    "pandas>=3.0.5",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.0",
    "uvicorn[standard]>=0.52.4",
]
